#!/bin/bash
# Start AutoMaker with CLIProxyAPI for Claude Code subscription
#
# This script handles everything:
# 1. Validates prerequisites (binary, config, OAuth token)
# 2. Prompts for Claude login if no OAuth token found
# 3. Starts CLIProxyAPI if not already running
# 4. Verifies the proxy is healthy
# 5. Starts AutoMaker in web or electron mode
#
# Usage: ./start-with-proxy.sh [web|electron]

set -e

# --- Configuration ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLI_PROXY_DIR="$HOME/code/utilities/CLIProxyAPI"
CLI_PROXY_BIN="$CLI_PROXY_DIR/cli-proxy-api"
CLI_PROXY_CONFIG_DIR="$HOME/.cli-proxy-api"
CLI_PROXY_CONFIG="$CLI_PROXY_CONFIG_DIR/config.yaml"
PROXY_PORT=8317
PROXY_LOG="/tmp/cliproxyapi.log"
PROXY_PID=""
PROXY_STARTED_BY_US=false

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m' # No Color

info()  { echo -e "${BLUE}${BOLD}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}${BOLD}[ok]${NC}    $*"; }
warn()  { echo -e "${YELLOW}${BOLD}[warn]${NC}  $*"; }
fail()  { echo -e "${RED}${BOLD}[fail]${NC}  $*"; }
step()  { echo -e "\n${BOLD}$*${NC}"; }

# --- Cleanup ---
cleanup() {
    if [ "$PROXY_STARTED_BY_US" = true ] && [ -n "$PROXY_PID" ]; then
        echo ""
        info "Shutting down CLIProxyAPI (PID: $PROXY_PID)..."
        kill "$PROXY_PID" 2>/dev/null || true
        wait "$PROXY_PID" 2>/dev/null || true
        ok "CLIProxyAPI stopped"
    fi
}
trap cleanup EXIT INT TERM

# --- Helpers ---
check_port() {
    if command -v lsof &>/dev/null; then
        lsof -i ":$PROXY_PORT" -sTCP:LISTEN &>/dev/null && return 0
    fi
    ss -tlnp 2>/dev/null | grep -q ":$PROXY_PORT" && return 0
    netstat -tlnp 2>/dev/null | grep -q ":$PROXY_PORT" && return 0
    return 1
}

# --- Step 1: Validate prerequisites ---
check_prerequisites() {
    step "1. Checking prerequisites..."

    # Check CLIProxyAPI binary
    if [ ! -x "$CLI_PROXY_BIN" ]; then
        fail "CLIProxyAPI binary not found at: $CLI_PROXY_BIN"
        echo ""
        echo "  Install it:"
        echo "    cd ~/code/utilities"
        echo "    git clone https://github.com/router-for-me/CLIProxyAPI.git"
        echo ""
        exit 1
    fi
    ok "CLIProxyAPI binary found"

    # Check or create config directory
    if [ ! -d "$CLI_PROXY_CONFIG_DIR" ]; then
        info "Creating config directory: $CLI_PROXY_CONFIG_DIR"
        mkdir -p "$CLI_PROXY_CONFIG_DIR"
    fi

    # Check or create config file
    if [ ! -f "$CLI_PROXY_CONFIG" ]; then
        info "Creating default config: $CLI_PROXY_CONFIG"
        cat > "$CLI_PROXY_CONFIG" <<'YAML'
# CLIProxyAPI Configuration (generated by start-with-proxy.sh)
host: "127.0.0.1"
port: 8317
auth-dir: "~/.cli-proxy-api"
debug: false
usage-statistics-enabled: false
request-retry: 3
max-retry-interval: 30
YAML
        ok "Config created"
    else
        ok "Config found"
    fi

    # Check Node.js
    if ! command -v node &>/dev/null; then
        fail "Node.js not found. AutoMaker requires Node.js >= 22"
        exit 1
    fi
    ok "Node.js $(node -v) found"
}

# --- Step 2: Check OAuth token ---
check_oauth() {
    step "2. Checking Claude OAuth token..."

    local token_files
    token_files=$(find "$CLI_PROXY_CONFIG_DIR" -maxdepth 1 -name "claude-*.json" 2>/dev/null)

    if [ -z "$token_files" ]; then
        warn "No Claude OAuth token found in $CLI_PROXY_CONFIG_DIR"
        echo ""
        echo -e "  You need to authenticate with Claude Code first."
        echo ""
        read -rp "  Run Claude login now? [Y/n] " answer
        case "$answer" in
            [nN]*)
                fail "Cannot continue without OAuth token"
                exit 1
                ;;
            *)
                info "Starting Claude login..."
                cd "$CLI_PROXY_DIR"
                ./cli-proxy-api --claude-login
                cd "$SCRIPT_DIR"

                # Re-check
                token_files=$(find "$CLI_PROXY_CONFIG_DIR" -maxdepth 1 -name "claude-*.json" 2>/dev/null)
                if [ -z "$token_files" ]; then
                    fail "Login did not produce an OAuth token"
                    exit 1
                fi
                ;;
        esac
    fi

    local count
    count=$(echo "$token_files" | wc -l)
    ok "Found $count OAuth token(s):"
    echo "$token_files" | while read -r f; do
        echo -e "     ${DIM}$(basename "$f")${NC}"
    done
}

# --- Step 3: Start CLIProxyAPI ---
start_proxy() {
    step "3. Starting CLIProxyAPI..."

    if check_port; then
        ok "CLIProxyAPI already running on port $PROXY_PORT"
        return 0
    fi

    info "Launching CLIProxyAPI on port $PROXY_PORT..."
    cd "$CLI_PROXY_DIR"
    nohup ./cli-proxy-api --config "$CLI_PROXY_CONFIG" > "$PROXY_LOG" 2>&1 &
    PROXY_PID=$!
    PROXY_STARTED_BY_US=true
    cd "$SCRIPT_DIR"

    # Wait for it to be ready
    for i in {1..15}; do
        sleep 1
        if check_port; then
            ok "CLIProxyAPI started (PID: $PROXY_PID)"
            return 0
        fi
        printf "."
    done

    echo ""
    fail "CLIProxyAPI failed to start within 15s"
    echo ""
    echo -e "  ${DIM}Logs:${NC}"
    tail -20 "$PROXY_LOG" 2>/dev/null | sed 's/^/    /'
    exit 1
}

# --- Step 4: Verify proxy health ---
verify_proxy() {
    step "4. Verifying proxy health..."

    local url="http://127.0.0.1:$PROXY_PORT"

    # Try a simple request to see if the proxy responds
    local status
    status=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 "$url" 2>/dev/null || echo "000")

    if [ "$status" = "000" ]; then
        fail "Proxy not responding at $url"
        echo -e "  ${DIM}Check logs: tail -f $PROXY_LOG${NC}"
        exit 1
    fi

    ok "Proxy responding at $url (HTTP $status)"
}

# --- Step 5: Start AutoMaker ---
start_automaker() {
    local mode="${1:-web}"

    step "5. Starting AutoMaker ($mode mode)..."

    cd "$SCRIPT_DIR"

    # Configure environment
    export ANTHROPIC_BASE_URL="http://127.0.0.1:$PROXY_PORT"
    export ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-proxy-localhost}"
    export AUTOMAKER_API_KEY="${AUTOMAKER_API_KEY:-dev}"
    export AUTOMAKER_AUTO_LOGIN=true

    echo ""
    echo -e "  ${DIM}Proxy:${NC}     $ANTHROPIC_BASE_URL"
    echo -e "  ${DIM}Login key:${NC} $AUTOMAKER_API_KEY"
    echo -e "  ${DIM}Frontend:${NC}  http://localhost:3007"
    echo -e "  ${DIM}Backend:${NC}   http://localhost:3008"
    echo ""

    case "$mode" in
        web)
            npm run dev:full
            ;;
        electron)
            npm run dev:electron
            ;;
        *)
            fail "Unknown mode: $mode (use 'web' or 'electron')"
            exit 1
            ;;
    esac
}

# --- Main ---
echo ""
echo -e "${BOLD}=== AutoMaker + CLIProxyAPI ===${NC}"

check_prerequisites
check_oauth
start_proxy
verify_proxy
start_automaker "${1:-web}"
